GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "jorge@email.com",
    "name": "Adilson",
    "password": "sadviasdbsdv"
}

###

POST http://localhost:3000/movimentacao/
Content-Type: application/json

{
    "category": "Bico",
    "title": "Site da Pizzaria",
    "value": 635.59,
    "type": "Entrada"
}

###
GET http://localhost:3000/movimentacao/1

###
PUT http://localhost:3000/movimentacao/1
Content-Type: application/json

{
    "category": "Trabalho",
    "title": "Sistema",
    "value": 5485.68,
    "type": "Entrada"
}

###
DELETE http://localhost:3000/movimentacao/9
###
GET http://localhost:3000/somadosvalores

###
GET http://localhost:3000/users/1/posts/

###
GET http://localhost:3000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNzU1MDQ2NjgzfQ.XMXw2tLl4OPtftfX-mIoJXYtiRE-oLX2AJBcSWYuE0Q

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email":"jorge@email.com",
    "password":"sadviasdbsdv"
}